### PR TITLE
add valgrind to x86_64 image

### PR DESCRIPTION
**Pull request by thehajime**
Signed-off-by: Hajime Tazaki <thehajime@gmail.com>

### CODE REVIEW

**Review by tavip — APPROVED** [review]

**Comment by thehajime** [comment]
@tavip it seems that I didn't add this feature to the latest Dockerfile.  
while x86_64:0.3 is based Ubuntu 16.04, 0.4 is based 14.04, resulting the valgrind test is failure due to missing autconf.h file (https://circleci.com/gh/libos-nuse/lkl-linux/1392).

images:
https://hub.docker.com/r/lkldocker/circleci-x86_64/builds/

Looks like the latest master branch doesn't contain the tagged commit (e.g., https://github.com/lkl/lkl-docker/commits/circleci-x86_64-0.3).  tag 0.4 is pure addition to the current master.

If I missed something about the instruction to create circleci image, please let me know.

**Comment by tavip** [comment]
I am not sure what happened. 0.3 was built by docker which means that the commits where part of master at some point:
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

Note: checking out 'fcc10e7efffadff4e4c2259fcd67c268c5bd2910'.
```
but it looks like they are not there anymore:

```
git show origin/master  fcc10e7efffadff4e4c2259fcd67c268c5bd2910
fatal: bad object fcc10e7efffadff4e4c2259fcd67c268c5bd2910
```
In any case, I still have the old commits on my machine and I will fix up things manually.

**Comment by thehajime** [comment]
Hmm, thanks for the info.

I'm not sure either but I may accidentally overwrite the lkl-docker/master during my push.
Please go ahead to fix the issue: sorry for the trouble.

**Comment by tavip** [comment]
No worries, the workflow is too flaky and we should find a better one. Maybe we could automate the tags push with a circleci build for lkldocker :)

Also, looks like circleci-x86_64:0.5 is published.

**Comment by thehajime** [comment]
thanks.

now i'm testing a fix for valgrind nightly build (https://circleci.com/gh/libos-nuse/lkl-linux/1411).  I will update with the latest x86_image (tag 0.5) and make a PR soon.

**Pull request merged**
